Repository iiasa/message-ix-models, pull requests merged in 2022-05, with the labels that each got.

#69 Add pyam to mypy's ignore_missing_imports
  setup.cfg
Labels: ci

#68 Add new logo and diagram to Sphinx/RTD docs
  doc/_static/combined-logo-white.png
  doc/_static/combined-logo-white.svg
  doc/_static/favicon.svg
  doc/_static/message-ix-models-logo-white.svg
  doc/conf.py
  doc/whatsnew.rst
Labels: documentation, enhancement

#62 Improve session_context, add .testing.not_ci
  doc/api/testing.rst
  doc/whatsnew.rst
  message_ix_models/model/build.py
  message_ix_models/testing.py
  message_ix_models/tests/test_testing.py
  message_ix_models/tests/test_util.py
Labels: enhancement

#71 Run CI against multiple versions of `ixmp` and `message_ix`
  .github/workflows/pytest.yaml
  doc/whatsnew.rst
  pyproject.toml
  setup.cfg
Labels: enh, ci
