Repository iiasa/message-ix-models, pull requests merged in 2023-08, with the labels that each got.

#113 Handling flaky tests
  message_ix_models/tests/util/test_context.py
Labels: enh, ci

#114 Adapt to new RTD configuration style
  .readthedocs.yaml
  .readthedocs.yml
  doc/requirements.in
  doc/requirements.txt
Labels: doc, enh

#116 Migrate `message_data.reporting`
  .github/workflows/lint.yaml
  doc/api/report/default-config.rst
  doc/api/report/index.rst
  doc/index.rst
  doc/whatsnew.rst
  message_ix_models/cli.py
  message_ix_models/data/report/global.yaml
  message_ix_models/report/__init__.py
  message_ix_models/report/cli.py
  message_ix_models/report/computations.py
  message_ix_models/report/sim.py
  message_ix_models/report/util.py
  message_ix_models/testing.py
  message_ix_models/tests/report/__init__.py
  message_ix_models/tests/report/test_computations.py
  message_ix_models/tests/test_report.py
  message_ix_models/tests/util/test_logging.py
  message_ix_models/util/_logging.py
  message_ix_models/workflow.py
  pyproject.toml
Labels: enh
