Repository iiasa/message-ix-models, pull requests merged in 2024-01, with the labels that each got.

#143 Correct DOI URL in doc/api/model-snapshot
  doc/api/model-snapshot.rst
Labels: bug, doc

#145 Ensure --regions CLI option can be used twice
  .pre-commit-config.yaml
  message_ix_models/report/plot.py
  message_ix_models/testing/__init__.py
  message_ix_models/tests/util/test_click.py
  message_ix_models/util/click.py
Labels: bug

#144 Derive income categories for MESSAGE node lists
  .pre-commit-config.yaml
  doc/api/tools.rst
  doc/conf.py
  doc/whatsnew.rst
  message_ix_models/model/structure.py
  message_ix_models/tests/tools/test_wb.py
  message_ix_models/tools/wb.py
Labels: enh, structure

#146 Remove Python 3.10-exclusive kw_only dataclass argument temporarily
  message_ix_models/util/scenarioinfo.py
Labels: bug

#149 Delete unused DEMAND data file
  message_ix_models/data/test/MESSAGEix-GLOBIOM_1.1_R11_no-policy_baseline/DEMAND.csv.gz
Labels: bug

#75 Handle IEA extended world energy balances
  .gitignore
  MANIFEST.in
  doc/api/data-sources.rst
  doc/api/tools.rst
  doc/index.rst
  doc/pkg-data/codelists.rst
  doc/whatsnew.rst
  message_ix_models/data/commodity.yaml
  message_ix_models/data/sdmx/IEA_COUNTRY_IEA(2023).xml
  message_ix_models/data/sdmx/IEA_COUNTRY_OECD(2021).xml
  message_ix_models/data/sdmx/IEA_COUNTRY_OECD(2022).xml
  message_ix_models/data/sdmx/IEA_COUNTRY_OECD(2023).xml
  message_ix_models/data/sdmx/IEA_FLOW_IEA(2023).xml
  message_ix_models/data/sdmx/IEA_FLOW_OECD(2021).xml
  message_ix_models/data/sdmx/IEA_FLOW_OECD(2022).xml
  message_ix_models/data/sdmx/IEA_FLOW_OECD(2023).xml
  message_ix_models/data/sdmx/IEA_PRODUCT_IEA(2023).xml
  message_ix_models/data/sdmx/IEA_PRODUCT_OECD(2021).xml
  message_ix_models/data/sdmx/IEA_PRODUCT_OECD(2022).xml
  message_ix_models/data/sdmx/IEA_PRODUCT_OECD(2023).xml
  message_ix_models/data/sdmx/IIASA_ECE_AGENCIES(0.1).xml
  message_ix_models/data/test/iea/372f7e29-en.zip
  message_ix_models/data/test/iea/8624f431-en.zip
  message_ix_models/data/test/iea/cac5fa90-en.zip
  message_ix_models/project/ssp/structure.py
  message_ix_models/testing/cli.py
  message_ix_models/tests/project/test_ssp.py
  message_ix_models/tests/tools/iea/__init__.py
  message_ix_models/tests/tools/iea/test_web.py
  message_ix_models/tools/iea/__init__.py
  message_ix_models/tools/iea/web.py
  message_ix_models/util/sdmx.py
  pyproject.toml
Labels: enh

#151 Raise informative exception from ScenarioInfo.io_units()
  doc/whatsnew.rst
  message_ix_models/testing/__init__.py
  message_ix_models/tests/util/test_scenarioinfo.py
  message_ix_models/util/scenarioinfo.py
Labels: enh
