Repository iiasa/message-ix-models, pull requests merged in 2024-07, with the labels that each got.

#202 Adjust apply_spec() to reduce log verbosity
  doc/whatsnew.rst
  message_ix_models/model/build.py
  message_ix_models/tests/model/test_build.py
  message_ix_models/util/__init__.py
Labels: enh

#203 Bump GAMS version in CI workflows to adjust for ixmp changes
  .github/workflows/pytest-snapshots.yaml
  .github/workflows/pytest.yaml
Labels: ci

#195 Create option in `tools.costs` to keep fixed O&M costs same across vintages
  doc/api/tools-costs.rst
  doc/whatsnew.rst
  message_ix_models/tools/costs/config.py
  message_ix_models/tools/costs/demo.py
  message_ix_models/tools/costs/projections.py
Labels: enh

#208 Manual adjustments for `.model.transport` migration
  .github/workflows/pytest.yaml
  .readthedocs.yaml
  conftest.py
  doc/api/report/index.rst
  doc/api/tools-messagev.rst
  doc/global/energy/enduse/index.rst
  doc/index.rst
  doc/main.bib
  doc/transport/index.rst
  doc/transport/input.rst
  doc/transport/old.rst
  doc/transport/output.rst
  doc/whatsnew.rst
  message_ix_models/cli.py
  message_ix_models/model/transport/CHN_IND.py
  message_ix_models/model/transport/base.py
  message_ix_models/model/transport/build.py
  message_ix_models/model/transport/cli.py
  message_ix_models/model/transport/config.py
  message_ix_models/model/transport/data.py
  message_ix_models/model/transport/demand.py
  message_ix_models/model/transport/emission.py
  message_ix_models/model/transport/factor.py
  message_ix_models/model/transport/files.py
  message_ix_models/model/transport/freight.py
  message_ix_models/model/transport/groups.py
  message_ix_models/model/transport/ikarus.py
  message_ix_models/model/transport/ldv.py
  message_ix_models/model/transport/migrate.py
  message_ix_models/model/transport/non_ldv.py
  message_ix_models/model/transport/operator.py
  message_ix_models/model/transport/report.py
  message_ix_models/model/transport/roadmap.py
  message_ix_models/model/transport/structure.py
  message_ix_models/model/transport/testing.py
  message_ix_models/model/transport/util.py
  message_ix_models/model/transport/workflow.py
  message_ix_models/model/workflow.py
  message_ix_models/project/engage/workflow.py
  message_ix_models/project/navigate/__init__.py
  message_ix_models/testing/__init__.py
  message_ix_models/tests/model/transport/test_base.py
  message_ix_models/tests/model/transport/test_build.py
  message_ix_models/tests/model/transport/test_callback.py
  message_ix_models/tests/model/transport/test_config.py
  message_ix_models/tests/model/transport/test_data.py
  message_ix_models/tests/model/transport/test_demand.py
  message_ix_models/tests/model/transport/test_disutility.py
  message_ix_models/tests/model/transport/test_emission.py
  message_ix_models/tests/model/transport/test_factor.py
  message_ix_models/tests/model/transport/test_ikarus.py
  message_ix_models/tests/model/transport/test_ldv.py
  message_ix_models/tests/model/transport/test_migrate.py
  message_ix_models/tests/model/transport/test_operator.py
  message_ix_models/tests/model/transport/test_report.py
  message_ix_models/tests/model/transport/test_util.py
  message_ix_models/tools/messagev.py
  message_ix_models/util/__init__.py
  message_ix_models/util/graphviz.py
  pyproject.toml
Labels: enh, transport
