Repository iiasa/message-ix-models, pull requests merged in 2024-04, with the labels that each got.

#161 Fetch non-packaged data using "mix-models fetch"
  doc/data.rst
  doc/whatsnew.rst
  message_ix_models/data/ssp/1710759470883-ssp_basic_drivers_release_3.0.1_full.csv.gz
  message_ix_models/project/ssp/data.py
  message_ix_models/tests/project/test_ssp.py
  message_ix_models/util/pooch.py
Labels: doc, enh

#165 Mark incompatible dask-python-combination-tests as XFail
  message_ix_models/tests/tools/iea/test_web.py
Labels: bug

#99 Add technoeconomic cost projections and related data
  .gitignore
  doc/api/tools-costs.rst
  doc/api/tools.rst
  doc/index.rst
  doc/whatsnew.rst
  message_ix_models/data/costs/energy/cost_reduction_energy.csv
  message_ix_models/data/costs/energy/first_year_energy.csv
  message_ix_models/data/costs/energy/scenarios_reduction_energy.csv
  message_ix_models/data/costs/energy/tech_map_energy.csv
  message_ix_models/data/costs/materials/first_year_materials.csv
  message_ix_models/data/costs/materials/tech_map_materials.csv
  message_ix_models/data/iea/WEO_2022_PG_Assumptions_STEPSandNZE_Scenario.xlsb
  message_ix_models/data/intratec/intratec_data.xlsx
  message_ix_models/data/node/R11.yaml
  message_ix_models/data/node/R12.yaml
  message_ix_models/data/node/R20.yaml
  message_ix_models/tests/tools/costs/__init__.py
  message_ix_models/tests/tools/costs/test_decay.py
  message_ix_models/tests/tools/costs/test_gdp.py
  message_ix_models/tests/tools/costs/test_projections.py
  message_ix_models/tests/tools/costs/test_regional_differentiation.py
  message_ix_models/tools/costs/__init__.py
  message_ix_models/tools/costs/config.py
  message_ix_models/tools/costs/decay.py
  message_ix_models/tools/costs/demo.py
  message_ix_models/tools/costs/gdp.py
  message_ix_models/tools/costs/projections.py
  message_ix_models/tools/costs/regional_differentiation.py
  message_ix_models/tools/exo_data.py
  message_ix_models/util/scenarioinfo.py
  pyproject.toml
Labels: enh

#166 Update pooch URL for SSPUpdate data
  .github/codecov.yml
  message_ix_models/tests/tools/iea/test_web.py
  message_ix_models/tools/iea/web.py
  message_ix_models/util/pooch.py
  pyproject.toml
Labels: ci

#110 Integrate included message_doc contents
  doc/_static/custom.css
  doc/conf.py
  doc/global/Makefile
  doc/global/README.rst
  doc/global/annex/index.rst
  doc/global/bibs/main.bib
  doc/global/conf.py
  doc/global/energy/tech.rst
  doc/global/energy/tech_addon.rst
  doc/global/further-reading.rst
  doc/global/index.rst
  doc/global/land_use/emulator.rst
  doc/global/macro.rst
  doc/global/make.bat
  doc/global/requirements.txt
  doc/global/z_bibliography.rst
  doc/index.rst
  doc/main.bib
  doc/messageix-globiom.bib
  doc/messageix-globiom.ris
  doc/whatsnew.rst
Labels: doc

#174 Improve .util.migrate
  doc/migrate.rst
  doc/whatsnew.rst
  message_ix_models/util/migrate.py
  pyproject.toml
  util/1-prep.sh
  util/2-migrate.sh
  util/reset.sh
  util/settings.sh
Labels: enh

#179 Remove workaround for #173
  .github/workflows/pytest.yaml
Labels: ci

#157 Create "Quick starting guide to running MESSAGEix-GLOBIOM" for occasional users
  doc/api/model-snapshot.rst
  doc/cli.rst
  doc/conf.py
  doc/index.rst
  doc/install.rst
  doc/quickstart.rst
  doc/whatsnew.rst
Labels: doc, enh

#182 Adjust packaging
  pyproject.toml
Labels: ci

#184 Use "macos-13" runner in "pytest" workflow
  .github/workflows/pytest.yaml
Labels: ci
