Repository iiasa/message-ix-models, pull requests merged in 2025-02, with the labels that each got.

#279 Add documentation for running MESSAGEix on UniCC
  doc/distrib/overview.rst
  doc/distrib/unicc.rst
  doc/index.rst
  doc/whatsnew.rst
Labels: doc, enh

#292 Check out correct ref in "pytest" CI job
  .github/workflows/pytest.yaml
Labels: bug, ci

#291 Add `.util.slurm` and CLI
  doc/api/util.rst
  doc/conf.py
  doc/distrib.rst
  doc/howto/index.rst
  doc/howto/migrate.rst
  doc/howto/quickstart.rst
  doc/howto/release.rst
  doc/howto/unicc.rst
  doc/index.rst
  doc/repro.rst
  doc/whatsnew.rst
  message_ix_models/cli.py
  message_ix_models/tests/test_cli.py
  message_ix_models/tests/util/test_slurm.py
  message_ix_models/util/slurm.py
Labels: enh

#295 Confirm support for minimum versions
  .github/workflows/pytest.yaml
  message_ix_models/model/material/build.py
  message_ix_models/model/material/data_petro.py
  message_ix_models/model/material/data_util.py
  message_ix_models/model/material/material_demand/material_demand_calc.py
  message_ix_models/model/transport/base.py
  message_ix_models/model/transport/operator.py
  message_ix_models/testing/__init__.py
  message_ix_models/tests/model/transport/test_config.py
  message_ix_models/tests/model/transport/test_operator.py
  message_ix_models/tests/report/test_compat.py
  message_ix_models/types.py
  message_ix_models/util/__init__.py
  message_ix_models/util/_dataclasses.py
  message_ix_models/util/cache.py
Labels: bug, ci

#282 Add docs pages for 2025 projects
  .github/CODEOWNERS
  doc/index.rst
  doc/project/alps.rst
  doc/project/carbon-direct.rst
  doc/project/cfr.rst
  doc/project/circeular.rst
  doc/project/ecemf.rst
  doc/project/elevate.rst
  doc/project/geidco.rst
  doc/project/genie.rst
  doc/project/guide.rst
  doc/project/hyway.rst
  doc/project/newpathways.rst
  doc/project/nextgen-carbon.rst
  doc/project/ngfs.rst
  doc/project/prisma.rst
  doc/project/sparccle.rst
  doc/project/ssp.rst
  doc/project/uptake.rst
  doc/whatsnew.rst
Labels: doc, enh

#289 Transport improvements from 2025-W05
  .github/workflows/pytest.yaml
  .github/workflows/transport.yaml
  doc/api/report/index.rst
  doc/api/util.rst
  doc/conf.py
  doc/transport/input.rst
  doc/whatsnew.rst
  message_ix_models/data/sdmx/IIASA_ECE_CL_TRANSPORT_SCENARIO(1.0.0).xml
  message_ix_models/data/test/transport/MESSAGEix-Transport R12 YB 41eee_baseline.xlsx
  message_ix_models/data/transport/R12/pdt-cap.csv
  message_ix_models/data/transport/set.yaml
  message_ix_models/data/transport/technology.yaml
  message_ix_models/model/structure.py
  message_ix_models/model/transport/base.py
  message_ix_models/model/transport/build.py
  message_ix_models/model/transport/config.py
  message_ix_models/model/transport/demand.py
  message_ix_models/model/transport/files.py
  message_ix_models/model/transport/freight.py
  message_ix_models/model/transport/ikarus.py
  message_ix_models/model/transport/key.py
  message_ix_models/model/transport/ldv.py
  message_ix_models/model/transport/non_ldv.py
  message_ix_models/model/transport/operator.py
  message_ix_models/model/transport/plot.py
  message_ix_models/model/transport/report.py
  message_ix_models/model/transport/structure.py
  message_ix_models/model/transport/testing.py
  message_ix_models/model/transport/util.py
  message_ix_models/project/edits/__init__.py
  message_ix_models/report/compat.py
  message_ix_models/report/key.py
  message_ix_models/report/operator.py
  message_ix_models/report/sim.py
  message_ix_models/report/util.py
  message_ix_models/testing/__init__.py
  message_ix_models/testing/check.py
  message_ix_models/tests/model/transport/__init__.py
  message_ix_models/tests/model/transport/test_base.py
  message_ix_models/tests/model/transport/test_build.py
  message_ix_models/tests/model/transport/test_data.py
  message_ix_models/tests/model/transport/test_report.py
  message_ix_models/tests/model/transport/test_util.py
  message_ix_models/tests/test_report.py
  message_ix_models/tests/test_util.py
  message_ix_models/tests/util/test_sdmx.py
  message_ix_models/types.py
  message_ix_models/util/__init__.py
  message_ix_models/util/_convert_units.py
  message_ix_models/util/genno.py
  message_ix_models/util/sdmx.py
  pyproject.toml
Labels: enh, transport

#299 Test against ixmp/message-ix v3.10.0
  .github/workflows/pytest.yaml
  doc/whatsnew.rst
Labels: enh, ci

#302 Fix CI for `message_ix` v3.10.0
  .github/workflows/pytest.yaml
Labels: ci
